<?php
// $Id: xoops_version.php, v 0.90 2005/04/10 14:00:00 David Gartner Exp $
//  ------------------------------------------------------------------------ //
//                XOOPS - PHP Content Management System                      //
//                    Copyright (c) 2000 XOOPS.org                           //
//                       <http://www.xoops.org/>                             //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //
$modversion['name'] = "net2ftp";
$modversion['version'] = 0.96;
$modversion['description'] = "net2ftp - a web based FTP client";
$modversion['author'] = "David Gartner (http://www.net2ftp.com)";
$modversion['credits'] = "Bassman (http://www.xoopshq.com) and Asim (designed the net2ftp Xoops logo)";
$modversion['help'] = "help.html";
$modversion['license'] = "The main code of net2ftp is released under the GNU GENERAL PUBLIC LICENSE. Submodules are released under their respective licenses.";
$modversion['official'] = 1;
$modversion['image'] = "logo.gif";
$modversion['dirname'] = "net2ftp";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
//$modversion['sqlfile']['mysql'] = "sql/create_tables.sql";
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
// DO NOT CREATE TABLES WITHIN XOOPS - USE NET2FTP'S OWN TABLES

// Admin things
$modversion['hasAdmin'] = 0;

// Main contents
$modversion['hasMain'] = 1;

//Blocks
$modversion['blocks'][1]['file'] = "index.php";
$modversion['blocks'][1]['name'] = "net2ftp";
$modversion['blocks'][1]['description'] = "net2ftp";
$modversion['blocks'][1]['show_func'] = "xoops_net2ftp";
$modversion['blocks'][1]['template'] = "net2ftp_blocks_login.html";

?>